import { openSansFont } from "../fonts";
import "../globals.css";
import { Footer } from "../ui/Footer";
import { Navigation } from "../ui/Navigation";
import Script from "next/script";
import { SupportedLanguage } from "../types";
import LocaleSwitcher from "../ui/LocaleSwitcher";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "de" }];
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: SupportedLanguage };
}) {
  return (
    <html lang={params.lang}>
      <Script
        async
        defer
        crossOrigin="anonymous"
        src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v16.0"
        nonce="QlVVPSyF"
      />
      <body className={openSansFont.className}>
        <div id="fb-root"></div>
        <main className="flex min-h-screen flex-col p-2 max-w-screen-xl m-auto">
          <div className="flex justify-end">
            <LocaleSwitcher />
          </div>
          <Navigation locale={params.lang} />
          <div className="p-4 max-w-screen-lg m-auto">{children}</div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
