import { openSansFont } from "./fonts";
import "./globals.css";
import { Navigation } from "./ui/Navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navLinks = [
  {
    name: "About",
    href: "/about",
  },
  {
    name: "Upcoming",
    href: "/upcoming",
  },
  {
    name: "Media",
    href: "/media",
  },
  {
    name: "Downloads",
    href: "/downloads",
  },
  {
    name: "contact",
    href: "/contact",
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={openSansFont.className}>
        <main className="flex min-h-screen flex-col p-2">
          <Navigation navLinks={navLinks} />
          <div className="p-4">{children}</div>
        </main>
      </body>
    </html>
  );
}
